=============================
 doctest_in_0-1-my_list.py
=============================

import of the module to be tested:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Test_1: base test:
    >>> bg = BaseGeometry()
    >>> bg.integer_validator("mimir", 12)
    >>> bg.integer_validator("pilas", "John")
    Traceback (most recent call last):
    ...
    TypeError: <name> must be an integer
    >>> bg.integer_validator("jhojan", 0)
    Traceback (most recent call last):
    ...
    ValueError: <name> must be greater than 0
    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
    ...
    ValueError: <name> must be greater than 0

Test_2: pass more arguments:
    >>> bg = BaseGeometry()
    >>> bg.integer_validator(12)
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'
    >>> bg = BaseGeometry()
    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
    >>> bg = BaseGeometry(123)
    Traceback (most recent call last):
    ...
    TypeError: BaseGeometry() takes no arguments

Test_3: pass inf number:
    >>> bg = BaseGeometry()
    >>> bg.integer_validator("perlaza", float('inf'))
    Traceback (most recent call last):
    ...
    TypeError: <name> must be an integer

Test_4: pass directory:
    >>> bg = BaseGeometry()
    >>> bg.integer_validator(["jhojan", "perlaza"], 2)

Test_5: Passing None to method
    >>> bg = BaseGeometry()
    >>> bg.integer_validator("age", None)
    Traceback (most recent call last):
    ...
    TypeError: <name> must be an integer

Test_6: test area method
    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

    >>> bg = BaseGeometry()
    >>> bg.area(5, 5)
    Traceback (most recent call last):
    	      ...
    TypeError: area() takes 1 positional argument but 3 were given

